# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_article_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='article'),
        ),
    ]
