# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20181031_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='littleclass',
        ),
        migrations.AddField(
            model_name='articleclass',
            name='alias',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articleclass',
            name='fatherid',
            field=models.IntegerField(default=0),
        ),
    ]
