# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0005_auto_20181031_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='keyword',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
